name: Staging ingest f1 data to gcs

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-terraform-staging:
    name: "Build and run docker"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Build Docker container
        id: build
        run: docker build -t f1-ingest:v1 ./data_ingestion

      - name: Run Docker container
        id: run
        run: docker run -it f1-ingest:v1